services:
 mongo:
   image: mongo:latest
   container_name: mongodb
   ports:
     - "27017:27017"
   volumes:
     - my-mongo-data:/data/db
   networks:
     - mern
 backend:
   build:
     context: ./backend
   ports:
     - "5000:5000"
   volumes:
     - ./backend:/usr/src/app
   networks:
     - mern
   depends_on:
     - mongo


 frontend:
   build:
     context: ./frontend
   container_name: frontend
   ports:
     - "5173:5173"
   networks:
     - mern
   depends_on:
     - backend

networks:
  mern:
    driver: bridge
volumes:
  my-mongo-data:
